# Generated by Django 2.2.10 on 2020-05-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.CharField(default='0.0', max_length=10, null=True)),
                ('cgst', models.IntegerField(default=0, null=True)),
                ('sgst', models.IntegerField(default=0, null=True)),
                ('generated_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bills',
            },
        ),
    ]
