# Generated by Django 2.2.10 on 2020-05-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restraunt',
            name='centre_gst',
            field=models.IntegerField(null=True, verbose_name='CGST'),
        ),
        migrations.AddField(
            model_name='restraunt',
            name='state_gst',
            field=models.IntegerField(null=True, verbose_name='SGST'),
        ),
    ]
